/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service;

import bean.User;
import database.FileDB;
import database.UserDB;
import java.awt.event.ActionEvent;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eyraf
 */
public class AdminFrame extends javax.swing.JFrame {

    private UserDB udb = new UserDB();
    private FileDB fdb = new FileDB();
    
    private List<User> allUsers;
    private List<String> nonAccessibleFolders;
    private User selectedUser;
    private int getSelectedIndexCB = 0;

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        usersPanel.setVisible(false);
        setNonAccessibleFolders.setVisible(false);
    }

    public void downloadAllUsers() {
        allUsers = udb.getAllUsers();
    }

    public void refresh() {
        usersPanel.setVisible(true);
        setNonAccessibleFolders.setVisible(false);

        downloadAllUsers();

        Object[] columnNames = Arrays.asList("ID", "Name", "Surname", "Username", "Password", "Status", "Position").toArray();
        Object[][] data = new Object[allUsers.size()][columnNames.length]; //-1 for admin accunt

        for (int i = 0; i < allUsers.size(); i++) {
            User u = allUsers.get(i);
            data[i] = Arrays.asList(u.getId(), u.getName(), u.getSurname(), u.getUsername(), u.getPassword(), u.getStatus(), u.getPosition()).toArray();
        }

        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblUsers.setModel(dtm);
    }

    public void fillAndUseComboBox() {
        JComboBox jcb = cbUsers;
        jcb.removeAllItems();

        for (int i = 0; i < allUsers.size(); i++) {
            User u = allUsers.get(i);
            jcb.addItem(u.getName());
        }
        
    }

    public void setNonAccessibleFolders() {
        setNonAccessibleFolders.setVisible(true);
        usersPanel.setVisible(false);

        downloadAllUsers();
        fillAndUseComboBox(); // fill and use jcombo box
        
        cbUsers.addActionListener((ActionEvent evt) -> { //selected
            int id = myBox(evt);
            
            FileDB fdb = new FileDB();
            nonAccessibleFolders = fdb.getNonAccessibleFolders(id);
            
            Object[] columnNames = Arrays.asList("ID","Name").toArray();
            Object[][] data = new Object[nonAccessibleFolders.size()][columnNames.length];
            
            for(int i=0;i<nonAccessibleFolders.size();i++){
                String folder = nonAccessibleFolders.get(i);
                data[i] = Arrays.asList(i+1,folder).toArray();
            }
            
            DefaultTableModel dtm = new DefaultTableModel(data,columnNames);
            tblNonAccessibleFolders.setModel(dtm);
        });
    }

    protected int myBox(ActionEvent evt) {
        if (cbUsers.getSelectedItem() != null) {
            String name = cbUsers.getSelectedItem().toString();
            
            for(int i=0;i<allUsers.size();i++){
                User u = allUsers.get(i);
                if(u.getName().equals(name)){
                    selectedUser = u;
                    getSelectedIndexCB = cbUsers.getSelectedIndex();
                    return u.getId();
                }
            }
        }
        
        return 9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usersPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnDeactive = new javax.swing.JButton();
        btnActive = new javax.swing.JButton();
        setNonAccessibleFolders = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNonAccessibleFolders = new javax.swing.JTable();
        cbUsers = new javax.swing.JComboBox<>();
        txtPathName = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(510, 600));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblUsersMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnDeactive.setText("Deactive");
        btnDeactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactiveActionPerformed(evt);
            }
        });

        btnActive.setText("Active");
        btnActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeactive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActive))
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnDeactive)
                    .addComponent(btnActive))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblNonAccessibleFolders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblNonAccessibleFolders);

        cbUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddItem.setText("Add");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setNonAccessibleFoldersLayout = new javax.swing.GroupLayout(setNonAccessibleFolders);
        setNonAccessibleFolders.setLayout(setNonAccessibleFoldersLayout);
        setNonAccessibleFoldersLayout.setHorizontalGroup(
            setNonAccessibleFoldersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setNonAccessibleFoldersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtPathName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setNonAccessibleFoldersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteItem)
                .addContainerGap())
        );
        setNonAccessibleFoldersLayout.setVerticalGroup(
            setNonAccessibleFoldersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setNonAccessibleFoldersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(setNonAccessibleFoldersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPathName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddItem))
                .addGap(18, 18, 18)
                .addGroup(setNonAccessibleFoldersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteItem))
                .addGap(60, 60, 60))
        );

        jMenu1.setText("Select");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("View Users List");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Set NonAccess Folders");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(setNonAccessibleFolders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(setNonAccessibleFolders, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        refresh();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveActionPerformed
        int getSelectedRowId = tblUsers.getSelectedRow();

        if (getSelectedRowId != -1) {
            int id = (Integer) tblUsers.getModel().getValueAt(getSelectedRowId, 0);

            if (udb.makeActive(id)) {
                refresh();
                JOptionPane.showMessageDialog(this, "Table successfully changed!");
            } else {
                JOptionPane.showMessageDialog(this, "There is a problem!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please select item from the table!");
        }
    }//GEN-LAST:event_btnActiveActionPerformed

    private void btnDeactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactiveActionPerformed
        int getSelectedRowId = tblUsers.getSelectedRow();

        if (getSelectedRowId != -1) {
            int id = (Integer) tblUsers.getModel().getValueAt(getSelectedRowId, 0);

            if (udb.deactivate(id)) {
                refresh();
                JOptionPane.showMessageDialog(this, "Table successfully changed!");
            } else {
                JOptionPane.showMessageDialog(this, "There is a problem!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please select item from the table!");
        }
    }//GEN-LAST:event_btnDeactiveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int getSelectedRowId = tblUsers.getSelectedRow();

        if (getSelectedRowId != -1) {
            int id = (Integer) tblUsers.getModel().getValueAt(getSelectedRowId, 0);

            if (udb.deleteUser(id)) {
                refresh();
                JOptionPane.showMessageDialog(this, "Table successfully changed!");
            } else {
                JOptionPane.showMessageDialog(this, "There is a problem!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please select item from the table!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblUsersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseReleased
        int getSelectedRowId = tblUsers.getSelectedRow();
        int id = (Integer) tblUsers.getModel().getValueAt(getSelectedRowId, 0);

        if (id == 9) {
            btnDeactive.setEnabled(false);
            btnDelete.setEnabled(false);
        } else {
            btnDeactive.setEnabled(true);
            btnDelete.setEnabled(true);
        }
    }//GEN-LAST:event_tblUsersMouseReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        int getSelectedRowId = tblNonAccessibleFolders.getSelectedRow();
        int id = (Integer) tblNonAccessibleFolders.getModel().getValueAt(getSelectedRowId, 0);
        
        String folderName = nonAccessibleFolders.get(id-1);
        int userId = selectedUser.getId();
        
        if(fdb.deleteNonAccessibleFolders(userId, folderName)){
            JOptionPane.showMessageDialog(this, "Table changed!");
            cbUsers.setSelectedIndex(getSelectedIndexCB);
        }else{
            JOptionPane.showMessageDialog(this, "There is a problem!");
        }
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setNonAccessibleFolders();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
      String pathName = txtPathName.getText();
      if(fdb.addNonAccessibleFolders(pathName, selectedUser.getId())){
          JOptionPane.showMessageDialog(this, "Table changed!");
          txtPathName.setText("");
          cbUsers.setSelectedIndex(getSelectedIndexCB); // refresh nonAccessibleFoldersList and combo box selected item
      }else{
          JOptionPane.showMessageDialog(this, "There is a problem!");
      }
    }//GEN-LAST:event_btnAddItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActive;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnDeactive;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JComboBox<String> cbUsers;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel setNonAccessibleFolders;
    private javax.swing.JTable tblNonAccessibleFolders;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtPathName;
    private javax.swing.JPanel usersPanel;
    // End of variables declaration//GEN-END:variables
}
